title: Richard Basile
author: Richard Basile
description: First Mate, Pirate Ship Revenge
url: "https://richardbasile.github.io"
baseurl: ""
repository: richardbasile/richardbasile.github.io

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

markdown: kramdown
permalink: /:title/
header_pages:
  - index.html
  - archive.md
  - connect.md
  - resume/index.html