title: Richard Basile
description: Fueled by faith, family, and the long run.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  name: Richard Basile
  bio: Fueled by faith, family, and the long run.
  links:
    - label: Facebook
      icon: fab fa-facebook
      url: https://facebook.com/buckeyestrides
    - label: Instagram
      icon: fab fa-instagram
      url: https://instagram.com/buckeyestrides
    - label: Pinterest
      icon: fab fa-pinterest
      url: https://pinterest.com/buckeyestrides
    - label: YouTube
      icon: fab fa-youtube
      url: https://youtube.com/@buckeyestrides
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://linkedin.com/in/richardbasile

markdown: kramdown

# Custom settings
permalink: /:title/         # Use filename as URL
header_pages:
  - index.md
  - links.md
